version: 2

project_name: bw
builds:
  - main: ./cmd/bw
    binary: bw
    ldflags:
      - -s -w
      - -X github.com/vanderheijden86/beadwork/pkg/version.Version=v{{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap publishing
brews:
  - name: bw
    repository:
      owner: vanderheijden86
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/vanderheijden86/beadwork
    description: "Graph-aware task management TUI for beads projects"
    license: "MIT"
    install: |
      bin.install "bw"
    test: |
      system "#{bin}/bw", "--version"
