version: 2

project_name: b9s
builds:
  - main: ./cmd/b9s
    binary: b9s
    ldflags:
      - -s -w
      - -X github.com/vanderheijden86/beadwork/pkg/version.Version=v{{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap publishing
brews:
  - name: b9s
    repository:
      owner: vanderheijden86
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/vanderheijden86/beadwork
    description: "Fast, focused TUI viewer and editor for beads projects"
    license: "MIT"
    install: |
      bin.install "b9s"
    test: |
      system "#{bin}/b9s", "--version"
